# Generated by Django 3.1.2 on 2020-10-22 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_user_followed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followed_by',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
