# Generated by Django 3.1.3 on 2021-11-25 16:54

from django.db import migrations, models
import jwt_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_user_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_address',
            field=models.CharField(max_length=50, null=True, unique=True, validators=[jwt_auth.models.isLowerCase]),
        ),
        migrations.AlterField(
            model_name='user',
            name='nonce',
            field=models.IntegerField(default=jwt_auth.models.random_string),
        ),
    ]
