# Generated by Django 3.1.3 on 2021-11-25 16:58

from django.db import migrations, models
import jwt_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0006_auto_20211125_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nonce',
            field=models.BigIntegerField(default=jwt_auth.models.random_string),
        ),
    ]
