# Generated by Django 3.1.2 on 2020-10-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('camera', models.CharField(blank=True, max_length=50)),
                ('lens', models.CharField(blank=True, max_length=50)),
                ('image', models.CharField(max_length=400)),
                ('location', models.CharField(max_length=75)),
            ],
        ),
    ]
