# Generated by Django 3.1.2 on 2020-10-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_categories', '0001_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='categories',
            field=models.ManyToManyField(related_name='photos', to='photo_categories.PhotoCategory'),
        ),
    ]
