# Generated by Django 3.1.2 on 2020-10-21 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0003_photo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
